version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devPa55w0rd
      MONGO_INITDB_DATABASE: hradmin_system
    ports:
      - 27017:27017
    volumes:
      - ./app/api/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./app/api/db/data:/data/db
  

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=devuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=devPa55w0rd
      - ME_CONFIG_MONGODB_URL=mongodb://devuser:devPa55w0rd@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=devuser
      - ME_CONFIG_BASICAUTH_PASSWORD=devPa55w0rd
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"